name: personal_card
description: A new Flutter project.
publish_to: 'none' 


environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/IMG_6418.jpg

  fonts:
     - family: IndieFlower
       fonts:
         - asset: fonts/IndieFlower-Regular.ttf